version: '3.5'
services:
  docker-mysql:
    image: mysql:latest
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'whateverdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: