version: "3.5"
services:
  network:
    command: bash -c ["if [ ! "$(docker network ls | grep db-docker_default)" ]; then
      echo "Creating db-docker_default network ..."
      docker network create db-docker_default
      else
      echo "db-docker_default network exists."
      fi"]
  mysql:
    image: mysql:8.0
    container_name: Event_db_container
    build:
      context: src/main/resources/database/
    ports:
      - "8083:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
networks:
  default:
    external:
      name: db-docker_default

